# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

# This file configures the bookshelf application frontend. The frontend serves
# public web traffic.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bookshelf-frontend-latest
  labels:
    app: bookshelf
    version: latest

# The bookshelf frontend replica set ensures that at least 2
# instances of the bookshelf app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/kubernetes-engine/docs/pods/
spec:
  replicas: 2

  template:
    metadata:
      labels:
        app: bookshelf
        tier: frontend
        version: latest
  
    spec:
      containers:
      - name: bookshelf-app
        # Set the Docker image your deployment should run
        image:
        env:
            - name: BOOKSHELF_BUCKET
              value: cloud-schulung-shared
            - name: BOOKSHELF_STORAGE_TYPE
              value: cloudsql
              # Set the database name to your group's database
            - name: SQL_DB_NAME
              value:
            - name: SQL_USER_NAME
              value: root
            - name: SQL_PASSWORD
              value: myRootPassword1234
            - name: SQL_REGION
              value: eu-west-1
            - name: SQL_HOST
              value: cloud-schulung-mysql.ce3ov7rw7pfc.eu-west-1.rds.amazonaws.com
            - name: SQL_PORT
              value: "3306"
            - name: AWS_REGION
              value: eu-west-1  
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always

        # The bookshelf process listens on port 8080 for web traffic by default.
        ports:
        - name: http-server
          containerPort: 8080
